### ISSUE TITLE
2014cacg data from #moardata

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance-data#11]
https://www.facebook.com/groups/moardata/819334451420185/

**Comment by gregmarra** [comment]
```
qm1, 3256, 115, 4171, 4159, 751, 2813, 27, 71
qm2, 1868, 604, 840, 2144, 1351, 670, 51, 86
qm3, 5026, 701, 1967, 4904, 649, 668, 48, 28
qm4, 4765, 8, 5104, 5023, 114, 846, 16, 147
qm5, 2367, 2489, 4186, 2473, 100, 256, 22, 31
qm6, 971, 766, 2854, 1458, 4255, 253, 199, 42
qm7, 4990, 4159, 115, 2643, 668, 604, 105, 89
qm8, 5026, 4765, 2144, 5104, 701, 2813, 13, 118
qm9, 256, 751, 5023, 1967, 670, 100, 35, 46
qm10, 1458, 1868, 2367, 4171, 114, 253, 37, 33
qm11, 2473, 4990, 4186, 766, 1351, 649, 28, 82
qm12, 8, 2643, 2489, 840, 4904, 2854, 17, 28
qm13, 971, 4255, 668, 3256, 846, 256, 80, 52
qm14, 253, 2813, 1868, 115, 1967, 5104, 116, 46
qm15, 670, 5026, 2367, 751, 1458, 1351, 28, 92
qm16, 8, 766, 604, 4186, 2643, 4765, 83, 53
qm17, 701, 840, 649, 4255, 4171, 100, 28, 51
qm18, 114, 4159, 4904, 2473, 2489, 846, 43, 102
qm19, 5023, 4990, 2854, 2144, 3256, 971, 18, 97
qm20, 2813, 256, 766, 8, 1351, 1868, 116, 127
qm21, 649, 670, 4255, 115, 253, 2643, 48, 37
qm22, 5104, 2367, 604, 1967, 4904, 2489, 34, 83
qm23, 2144, 1458, 100, 668, 4159, 3256, 93, 33
qm24, 2473, 4171, 751, 4990, 4765, 971, 63, 148
qm25, 701, 846, 2854, 4186, 840, 5023, 132, 37
qm26, 114, 2489, 1868, 5026, 649, 2813, 164, 52
qm27, 5104, 668, 670, 8, 4159, 2367, 61, 53
qm28, 100, 4990, 4904, 115, 4765, 1458, 18, 110
qm29, 1967, 2643, 5023, 4186, 4171, 971, 26, 117
qm30, 4255, 701, 751, 604, 2854, 114, 5, 154
qm31, 253, 846, 2144, 1351, 5026, 2473, 100, 47
qm32, 840, 256, 115, 3256, 766, 4765, 15, 73
qm33, 649, 5023, 971, 4904, 2813, 2367, 180, 25
qm34, 100, 4159, 4186, 1868, 4255, 2854, 71, 41
qm35, 701, 668, 1351, 253, 2489, 751, 92, 52
qm36, 604, 3256, 4990, 114, 5026, 8, 114, 32
qm37, 2144, 4171, 1967, 766, 846, 670, 50, 161
qm38, 2643, 256, 1458, 5104, 2473, 840, 56, 87
qm39, 4159, 253, 1351, 4765, 668, 5023, 66, 44
qm40, 3256, 751, 4904, 4186, 1868, 649, 22, 84
qm41, 115, 766, 2144, 114, 2367, 971, 61, 290
qm42, 8, 2854, 256, 4171, 5026, 1458, 16, 42
qm43, 840, 2489, 670, 4990, 1967, 4255, 97, 73
qm44, 2813, 2643, 2473, 100, 701, 604, 22, 256
qm45, 846, 751, 668, 5104, 114, 766, 121, 46
qm46, 649, 8, 253, 4159, 2144, 256, 42, 49
qm47, 4904, 1351, 4765, 670, 3256, 2854, 97, 53
qm48, 4186, 4255, 2813, 840, 2367, 2643, 50, 37
qm49, 2473, 1967, 971, 5026, 1868, 115, 167, 83
qm50, 604, 1458, 846, 701, 2489, 5023, 164, 22
qm51, 5104, 100, 253, 4990, 4171, 1351, 58, 42
qm52, 2813, 114, 668, 256, 4186, 670, 72, 31
qm53, 1868, 751, 4765, 2643, 2144, 4255, 117, 18
qm54, 5023, 4904, 5026, 4159, 766, 840, 12, 23
qm55, 4171, 5104, 2854, 604, 649, 2473, 18, 88
qm56, 100, 115, 2489, 971, 8, 846, 32, 265
qm57, 2367, 3256, 1967, 1458, 701, 4990, 57, 160
qf1m1, 971, 846, 2489, 4765, 4990, 751, 206, 28
qf1m2, 971, 846, 2489, 4765, 4990, 751, 216, 39
qf2m1, 100, 701, 4171, 604, 114, 4186, 69, 152
qf2m2, 2473, 701, 4171, 604, 114, 4186, 38, 129
qf3m1, 1458, 1868, 115, 670, 3256, 8, 88, 90
qf3m2, 1458, 1868, 115, 670, 3256, 8, 53, 52
qf3m3, 1458, 1868, 115, 670, 3256, 8, 78, 66
qf4m1, 1351, 766, 668, 4159, 2813, 649, 53, 69
qf4m2, 1351, 766, 668, 4159, 2813, 649, 61, 118
sf1m1, 971, 846, 2489, 604, 114, 4186, 186, 181
sf1m2, 971, 846, 2489, 604, 114, 4186, 241, 110
sf2m1, 1458, 1868, 115, 4159, 2813, 649, 47, 144
sf2m2, 1458, 1868, 115, 4159, 2813, 649, 58, 43
sf2m3, 1458, 1868, 115, 4159, 2813, 649, 124, 59
f1m1, 971, 846, 2489, 1458, 1868, 115, 270, 113
f1m2, 971, 846, 2489, 1458, 1868, 115, 200, 62
```

But throws a 500.

**Comment by gregmarra** [comment]
```
'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-2.381592103194424292/controllers/admin/admin_match_controller.py", line 131, in post
    for match in matches]
AttributeError: 'list' object has no attribute 'get'
```

**Comment by fangeugene** [comment]
Fixed the 500 error and added the data.
